openapi: 3.1.0

info:
  title: D&D Game Plugin API
  version: "1.0.0"
  description: API para gestionar datos de campañas de D&D.

servers:
  - url: https://dnd-plugin-basic.onrender.com

paths:
  /store_character:
    post:
      summary: Guarda un personaje.
      operationId: storeCharacter
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Nombre del personaje.
                race:
                  type: string
                  description: Raza del personaje.
                class:
                  type: string
                  description: Clase del personaje.
                level:
                  type: integer
                  description: Nivel del personaje.
                alignment:
                  type: string
                  description: Alineamiento del personaje.
                hit_points:
                  type: integer
                  description: Puntos de golpe del personaje.
                equipment:
                  type: array
                  items:
                    type: string
                  description: Equipo del personaje.
                notes:
                  type: string
                  description: Notas adicionales.
      responses:
        "201":
          description: Personaje guardado con éxito.

  /retrieve_characters:
    get:
      summary: Recupera todos los personajes.
      operationId: retrieveCharacters
      responses:
        "200":
          description: Lista de personajes.
          content:
            application/json:
              schema:
                type: object
                properties:
                  characters:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        type:
                          type: string
                        attributes:
                          type: object
                        skills:
                          type: array
                          items:
                            type: string
                        description:
                          type: string
